name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axiom-sdk-rust-client:
    runs-on: ubuntu-latest-64core-256ram
    steps:
      - uses: actions/checkout@v3
      - name: Build rust client
        run: |
          cargo build --verbose
      - name: Install KZG params
        run: |
          mkdir params
          for k in {5..21}
          do
            wget "https://axiom-crypto.s3.amazonaws.com/challenge_0078/kzg_bn254_${k}.srs"
          done
          mv *.srs params/
      - name: Test rust client
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          cargo test -- --test-threads=1
      - name: Test examples
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          mkdir data
          # cargo run --example keccak -- --input sdk/data/keccak_input.json -k 15 -c sdk/data/keccak_config.json keygen
          # cargo run --example keccak -- --input sdk/data/keccak_input.json -k 15 -c sdk/data/keccak_config.json run
          cargo run --example rlc -- --input sdk/data/rlc_input.json -k 15 -c sdk/data/rlc_config.json keygen
          cargo run --example rlc -- --input sdk/data/rlc_input.json -k 15 -c sdk/data/rlc_config.json run
          cargo run --example account_age -- --input sdk/data/account_age_input.json -k 15 keygen
          cargo run --example account_age -- --input sdk/data/account_age_input.json -k 15 run
          cargo run --example quickstart -- --input sdk/data/quickstart_input.json -k 15 keygen
          cargo run --example quickstart -- --input sdk/data/quickstart_input.json -k 15 run
