name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axiom-sdk-rust-client:
    runs-on: ubuntu-latest-64core-256ram
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v3
      - name: Give GitHub Actions access to axiom-crypto/axiom-eth-working
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.AXIOM_ETH_DEPLOY_PRIVATE_KEY }}
      - name: Build rust client
        run: |
          cargo build --verbose
      - name: Install KZG params
        run: |
          mkdir params
          for k in {5..21}
          do
            wget "https://axiom-crypto.s3.amazonaws.com/challenge_0085/kzg_bn254_${k}.srs"
          done
          mv *.srs params/
          mkdir circuit/params
          cp params/*.srs circuit/params/
      - name: Test rust client
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          cargo test -- --test-threads=1
      - name: Test examples
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          mkdir data
          cargo run --example keccak -- run --input sdk/data/keccak_input.json --config sdk/data/keccak_config.json --aggregate --auto-config-aggregation keygen
          cargo run --example keccak -- run --input sdk/data/keccak_input.json --config sdk/data/keccak_config.json --aggregate prove
          cargo run --example rlc -- run -c sdk/data/rlc_config.json keygen
          cargo run --example rlc -- run --input sdk/data/rlc_input.json prove
          cargo run --example account_age -- run -k 15 keygen
          cargo run --example account_age -- run --input sdk/data/account_age_input.json prove
          cargo run --example quickstart -- run -k 15 keygen
          cargo run --example quickstart -- run --input sdk/data/quickstart_input.json prove
